add format converters to importer

diff --git a/bin/import-media b/bin/import-media
--- a/bin/import-media
+++ b/bin/import-media
@@ -1,6 +1,7 @@
 #!/bin/bash
+set -e
 
-media=${MEDIA_DIR:-$HOME/Media} 
+media=${MEDIA_DIR:-$HOME/Media}
 tmp="/tmp/media"
 mkdir -p "$tmp"
 
@@ -57,8 +58,8 @@ function setCreateDate {
   exiftool -CreateDate="${d::4}:${d:4:2}:${d:6:2} ${d:9:2}:${d:11:2}:${d:13:2}" "$t" > /dev/null
   created=$(getCreateDate "$t")
   original="${t}_original"
-  if [[ "${t}_original" != "$tmp/$(basename "${t}_original")" ]]
-  then mv -f "${t}_original" "$original"
+  if [[ "$original" != "$tmp/$(basename "${t}_original")" ]]
+  then mv -f "$original" "$tmp/$(basename "${t}_original")"
   fi
   echo "$good Updated exif data for $t w new create date: ${created}"
 }
@@ -97,33 +98,86 @@ then
 
 fi
 
+dotype=${target##*.}
 ext=$(exiftool -FileTypeExtension "$target" 2> /dev/null | sed 's/^.*: //')
 
-# Convert m4v files into mp4
-if [[ "$ext" == "m4v" ]]
+if [[ \
+  "$ext" != "avi" &&\
+  "$ext" != "gif" &&\
+  "$ext" != "heic" &&\
+  "$ext" != "jpg" &&\
+  "$ext" != "m4v" &&\
+  "$ext" != "mov" &&\
+  "$ext" != "mp4" &&\
+  "$ext" != "png" \
+  ]]
+then echo "$fail Skipping file with unsupported FileTypeExtension $ext: $target" && exit 1
+fi
+
+########################################
+## Conversions: heic=>jpg, avi,m4v,mov=>mp4
+
+# Convert heic files into jpg
+if [[ "$ext" == "heic" ]]
 then
-  tmpTarget="$tmp/$(basename "$target" | sed 's/\.m4v/\.mp4/')"
+  if [[ -z "$(command -v heif-convert)" ]]
+  then echo "$fail Install heif-convert first" && exit 1
+  fi
+  tmpTarget="$tmp/$(basename "$target" | sed 's/\.'"$dotype"'/\.jpg/')"
   if [[ -f "$tmpTarget" ]]
   then rm -f "$tmpTarget"
   fi
-  echo "$warn Converting m4v-formatted $target into an mp4 at $tmpTarget"
-  ffmpeg -i "$target" -loglevel error -vcodec copy -acodec copy "$tmpTarget"
+  echo "$warn Converting heic-formatted $target into an jpg at $tmpTarget"
+  heif-convert "$target" "$tmpTarget" > /dev/null
+  target="$tmpTarget"
+  ext="jpg"
+fi
+
+# Convert mov files into mp4
+# Do we need to rm data streams? https://github.com/aminyazdanpanah/PHP-FFmpeg-video-streaming/issues/74
+if [[ "$ext" == "mov" ]]
+then
+  tmpTarget="$tmp/$(basename "$target" | sed 's/\.'"$dotype"'/\.mp4/')"
+  if [[ -f "$tmpTarget" ]]
+  then rm -f "$tmpTarget"
+  fi
+  echo "$warn Converting mov-formatted $target into an mp4 at $tmpTarget"
+  ffmpeg -i "$target" -loglevel error -f mp4 "$tmpTarget"
   setCreateDate "$tmpTarget" "$created"
   target="$tmpTarget"
   ext="mp4"
 fi
 
-if [[ \
-  "$ext" != "avi" &&\
-  "$ext" != "gif" &&\
-  "$ext" != "jpg" &&\
-  "$ext" != "mov" &&\
-  "$ext" != "mp4" &&\
-  "$ext" != "pdf" &&\
-  "$ext" != "png" \
-  ]]
-then echo "$fail Unknown FileTypeExtension $ext for $target" && exit 1
+# Convert m4v files into mp4
+if [[ "$ext" == "m4v" ]]
+then
+  tmpTarget="$tmp/$(basename "$target" | sed 's/\.'"$dotype"'/\.mp4/')"
+  if [[ -f "$tmpTarget" ]]
+  then rm -f "$tmpTarget"
+  fi
+  echo "$warn Converting m4v-formatted $target into an mp4 at $tmpTarget"
+  ffmpeg -i "$target" -loglevel error -f mp4 -vcodec copy -acodec copy "$tmpTarget"
+  setCreateDate "$tmpTarget" "$created"
+  target="$tmpTarget"
+  ext="mp4"
 fi
+
+# Convert avi files into mp4
+if [[ "$ext" == "avi" ]]
+then
+  tmpTarget="$tmp/$(basename "$target" | sed 's/\.'"$dotype"'/\.mp4/')"
+  if [[ -f "$tmpTarget" ]]
+  then rm -f "$tmpTarget"
+  fi
+  echo "$warn Converting avi-formatted $target into an mp4 at $tmpTarget"
+  ffmpeg -i "$target" -loglevel error -f mp4 "$tmpTarget"
+  setCreateDate "$tmpTarget" "$created"
+  target="$tmpTarget"
+  ext="mp4"
+fi
+
+########################################
+## Check digest & import
 
 full_digest=$(sha256sum "$target" | cut -d " " -f 1)
 digest=$(echo "$full_digest" | head -c 8)
