convert media index to json

diff --git a/bin/import-media b/bin/import-media
--- a/bin/import-media
+++ b/bin/import-media
@@ -66,24 +66,33 @@ fi
 
 target_hash=$(sha256sum "$target" | cut -d " " -f 1)
 
-index=$media/.index
+function getEntry {
+  jq '.["'"$target_hash"'"]' "$index" 2>&1 | tr -d '"'
+}
+
+function setEntry {
+  mv "$index" "$index.backup"
+  jq '.["'"$target_hash"'"] = "'"$1"'"' "$index.backup" > "$index"
+  rm "$index.backup"
+}
+
+index=$media/.index.json
 if [[ ! -f "$index" ]]
-then touch "$index"
+then echo '{}' > "$index"
 fi
 
-entry=$(grep -m1 "^$target_hash:" "$index" || true)
-if [[ -n "$entry" && "$entry" == *:* ]]
+entry=$(getEntry "$target_hash")
+if [[ "$entry" != "null" ]]
 then
-  path=${entry#*:}
-  if [[ -n "$path" ]]
+  if [[ -n "$entry" ]]
   then
-    echo "$good File has already been imported & is available at $path"
+    echo "$good File has already been imported & is available at $entry"
     if [[ "$dryrun" == "false" && "$remove" == "true" ]]
     then
-      dup_suffix=$(sha256sum "$media/$path" | cut -d " " -f 1 | head -c 8)
-      if [[ "$path" =~ .*-$dup_suffix\..* ]]
+      dup_suffix=$(sha256sum "$media/$entry" | cut -d " " -f 1 | head -c 8)
+      if [[ "$entry" =~ .*-$dup_suffix\..* ]]
       then rm -f "$target" && echo "$warn Removed $target"
-      else echo "$fail Invalid file exists at $path (expected suffix of $dup_suffix)" && exit 1
+      else echo "$fail Invalid file exists at $entry (expected suffix of $dup_suffix)" && exit 1
       fi
     fi
   else
@@ -240,8 +249,8 @@ then
   fi
   if [[ "$dryrun" == "false" ]]
   then
-    echo "$target_hash:$subpath" >> "$index"
-    echo "$warn Added index entry for $target_hash:$subpath"
+    setEntry "$subpath"
+    echo "$warn Added index entry for $target_hash: $subpath"
     if [[ "$remove" == "true" ]]
     then rm -f "$target" && echo "$warn Removed $target"
     fi
@@ -273,7 +282,7 @@ elif [[ "$dryrun" == "false" ]]
 then
   cp -i "$tmp_target" "$path"
   echo "$good Imported $target to $subpath"
-  echo "$target_hash:$subpath" >> "$index"
+  setEntry "$subpath"
   if [[ "$remove" == "true" ]]
   then
     dup_suffix=$(sha256sum "$path" | cut -d " " -f 1 | head -c 8)
