init remove media helper

diff --git a/bin/import-media b/bin/import-media
--- a/bin/import-media
+++ b/bin/import-media
@@ -1,19 +1,17 @@
 #!/bin/bash
 
-year_prefix="20"
+media=${MEDIA_DIR:-$HOME/Media} 
 
 fail="❌"
 good="✅"
 warn="⚠️ "
 
-media=${MEDIA_DIR:-$HOME/Media} 
+if [[ -z "$(command -v exiftool)" ]]
+then echo "$fail Install exiftool first" && exit 1
+fi
 
 if [[ ! -d "$media" ]]
 then mkdir -p "$media"
-fi
-
-if [[ -z "$(command -v exiftool)" ]]
-then echo "$fail Install exiftool first" && exit 1
 fi
 
 target="$1"
@@ -40,38 +38,43 @@ function getCreateDate {
     | sed 's/://g' \
     | sed 's/ /-/g' \
     | sed 's/-$//' \
-    | sed 's/^-//' \
-    | sed 's/^'"$year_prefix"'//'
+    | sed 's/^-//'
 }
 
 created=$(getCreateDate "$target")
 if [[ -z "$created" ]]
 then
+  echo "$warn No available CreateDate exif data for $target"
 
-  if [[ "$target" =~ IMG-[[:digit:]]{8}-WA[[:digit:]]{4,}.* ]]
+  if [[ "$target" =~ (IMG|DOC|VID)-[[:digit:]]{8}-WA[[:digit:]]{4,}.* ]]
   then
     date="$(echo "$target" | cut -d "-" -f 2)-000000"
     exiftool -CreateDate="${date::4}:${date:4:2}:${date:6:2} 00:00:00" "$target"
     created=$(getCreateDate "$target")
+    echo "Updated exif data w new create date: ${created}"
   else
-    created="000000-000000" # TODO: check to see if the filename includes a date?
-    year_prefix="00"
+    created="00000000-000000" # TODO: check to see if the filename includes a date?
+    echo "Using unknown create date: ${created}"
   fi
 
-
-  echo "$warn No available CreateDate exif data for $target, using $created instead."
 fi
 
 full_digest=$(sha256sum "$target" | cut -d " " -f 1)
 digest=$(echo "$full_digest" | head -c 8)
 
-name="$media/$year_prefix${created::2}/$created-$digest.$ext"
+name="$created-$digest.$ext"
+path="$media/$name"
+trash=$media/.trash
 
-if [[ -f "$name" ]]
+if grep -qs "$full_digest" < "$trash"
+then echo "$warn $name has already been deleted, skipping import" && exit 0
+fi
+
+if [[ -f "$path" ]]
 then
-  dup_digest=$(sha256sum "$name" | cut -d " " -f 1)
+  dup_digest=$(sha256sum "$path" | cut -d " " -f 1)
   if [[ "$dup_digest" == "$full_digest" ]]
-  then echo "$good Destination $name already exists w the same digest as our target"
+  then echo "$good Destination $name already exists w the same digest as $target"
   else echo "$fail Destination $name already exists w DIFFERENT digest than $target"
   fi
   exit 0
@@ -95,13 +98,13 @@ then
 fi
 
 if [[ "$2" == "-n" ]]
-then echo "$good Copying $target to $name"
+then echo "$good Copying $target to $path"
 elif [[ "$2" == "-y" ]]
 then
-  if [[ ! -d "$(dirname "$name")" ]]
-  then mkdir -vp "$(dirname "$name")"
-  fi
-  cp -vi "$target" "$name"
+  cp -i "$target" "$path"
+  echo "$good Copied $target to $path"
+  chmod 644 "$path"
+
 else
   echo "Use the 2nd arg to specify whether or not you actually want to make changes"
   echo "  -n  No I don't want to make changes, show me what the changes would be"
