handle filenames that start with -

diff --git a/bin/import-media b/bin/import-media
--- a/bin/import-media
+++ b/bin/import-media
@@ -35,6 +35,8 @@ mkdir -p "$tmp"
 target="$1"
 if [[ ! -f "$target" ]]
 then echo "$fail File does not exist at $target" && exit 1
+elif [[ "$target" != "./"* && "$target" != "/"* ]]
+then target="./$target" # prefix helps handle files starting with '-' gracefully
 fi
 
 given_category="$2"
@@ -64,20 +66,26 @@ if [[ ! -f "$index" ]]
 then sqlite3 "$index" "create table media(hash varchar(64) primary key, path text);"
 fi
 
-target_hash=$(sha256sum "$target" | cut -d " " -f 1)
+target_hash=$(sha256sum -- "$target" | cut -d " " -f 1)
 
 ####################
 ## helper functions
 
 function getCreateDate {
-  exiftool -CreateDate "$1" 2> /dev/null \
-    | sed 's/.*  ://' \
-    | sed 's/: /:0/g' \
-    | sed 's/://g' \
-    | sed 's/\+.*//g' \
-    | sed 's/ /-/g' \
-    | sed 's/-$//' \
-    | sed 's/^-//'
+  function cleanDate {
+    sed 's/.*  ://' \
+      | sed 's/: /:0/g' \
+      | sed 's/://g' \
+      | sed 's/\+.*//g' \
+      | sed 's/ /-/g' \
+      | sed 's/-$//' \
+      | sed 's/^-//'
+  }
+  res=$(exiftool -CreateDate -- "$1" | cleanDate)
+  if [[ -n "$res" ]]
+  then echo "$res"
+  else exiftool -DateCreated -- "$1" | cleanDate
+  fi
 }
 
 function setCreateDate {
@@ -85,11 +93,11 @@ function setCreateDate {
   d="$2"
   date="${d::4}:${d:4:2}:${d:6:2} ${d:9:2}:${d:11:2}:${d:13:2}"
   #echo "Setting create date for file '$t' to '$date'"
-  if ! exiftool -ignoreMinorErrors -CreateDate="$date" "$t" > /dev/null
+  if ! exiftool -ignoreMinorErrors -CreateDate="$date" -- "$t" > /dev/null
   then
     echo "Attmpting to repair broken exif data..."
     # Rewrite all valid exif metadata if some was corrupted (see https://exiftool.org/faq.html#Q20)
-    if ! exiftool -all= -tagsfromfile @ -all:all -unsafe -icc_profile -CreateDate="$date" "$t" > /dev/null
+    if ! exiftool -all= -tagsfromfile @ -all:all -unsafe -icc_profile -CreateDate="$date" -- "$t" > /dev/null
     then echo "$fail Failed to set $t CreateDate to $d" && exit 1
     fi
   fi
@@ -148,7 +156,7 @@ then
 fi
 
 dotype=${target##*.}
-ext=$(exiftool -FileTypeExtension "$target" 2> /dev/null | sed 's/^.*: //')
+ext=$(exiftool -FileTypeExtension -- "$target" 2> /dev/null | sed 's/^.*: //')
 
 if [[ \
   "$ext" == "3gp" ||\
@@ -190,7 +198,7 @@ else
   echo "$fail Skipping file with unsupported FileTypeExtension $ext: $target" && exit 1
 fi
 
-if ! exiftool "$target" > /dev/null
+if ! exiftool -- "$target" > /dev/null
 then echo "Invalid exif data for $target" && exit 1
 fi
 
@@ -362,11 +370,20 @@ suffix=$(echo "$new_hash" | head -c 8)
 
 if [[ "$datename" == "true" ]]
 then
+  if [[ -z "$created" ]]
+  then echo "$fail Failed to determine a create date for $target"
+  fi
   name="$created-$suffix.$ext"
   subpath="$category/$name"
   path="$media/$subpath"
 else
-  name="$(basename "$tmp_target" "$ext" | tr -d "'" | tr ' _–,.()&' '-' | sed 's/-\+/-/g' | sed 's/-$//')-$suffix.$ext"
+  name="$(basename "$tmp_target" "$ext" \
+    | tr -d "'" \
+    | tr ' _–,.()&[]' '-' \
+    | sed 's/-\+/-/g' \
+    | sed 's/-$//' \
+    | sed 's/^-//' \
+  )-$suffix.$ext"
   subpath="$category/$name"
   path="$media/$subpath"
 fi
