fix remove-media

diff --git a/bin/remove-media b/bin/remove-media
--- a/bin/remove-media
+++ b/bin/remove-media
@@ -1,34 +1,60 @@
 #!/bin/bash
 
+########################################
+## Define Constants
+
 fail="❌"
 good="✅"
 
+########################################
+## Make sure required bins & files & dirs exist
+
+if [[ -z "$(command -v sqlite3)" ]]
+then echo "$fail Install sqlite3 first" && exit 1
+fi
+
 media=${MEDIA_DIR:-$HOME/Media} 
 mkdir -p "$media"
+
+########################################
+## Parse Args
+
+path="$1"
+fullpath="$media/$path"
+if [[ ! -f "$fullpath" ]]
+then echo "$fail File does not exist at $fullpath" && exit 1
+fi
+
+if [[ "$2" == "--dry-run" ]]
+then dryrun="true"
+else dryrun="false"
+fi
+
+########################################
+## Update Index
 
 index=$media/index.sqlite
 if [[ ! -f "$index" ]]
 then sqlite3 "$index" "create table media(hash varchar(64) primary key, path text);"
 fi
 
-target=$(basename "$1")
-
-entry=$(grep -m 1 "$target$" "$index" || true)
-
-path="${entry#*:}"
-if ! [[ -f "$path" ]]
-then echo "$fail Can't find a target at $path" && exit 1
-fi
-
-if [[ -n "$entry" && "$entry" == *:* ]]
-then
-  mv "$index" "$index.backup"
-  sed "s/$entry/${entry%:*}:/" < "$index.backup" > "$index"
-  rm "$index.backup"
+delete_query="update media set path = NULL where path = '$path';"
+if [[ "$dryrun" == "true" ]]
+then echo "Execute SQLite query: $delete_query"
 else
-  echo "$fail File is not in the index: $target" && exit 1
+  echo "Executing SQLite query: $delete_query"
+  if ! sqlite3 "$index" "$delete_query"
+  then echo "$fail Failed to update index entry for $path" && exit 1
+  fi
 fi
 
-rm -f "$path"
-find "$media/albums" -name "$target" -exec rm -f {} \;
-echo "$good Removed $path"
+########################################
+## Remove File?
+
+if [[ "$dryrun" == "true" ]]
+then echo "Remove $path"
+else
+  rm "$fullpath"
+  find "$media/albums" -name "$(basename "$path")" -exec rm {} \;
+  echo "$good Removed $path"
+fi
diff --git a/bin/verify-media b/bin/verify-media
--- a/bin/verify-media
+++ b/bin/verify-media
@@ -27,6 +27,15 @@ media=${MEDIA_DIR:-$HOME/Media}
 mkdir -p "$media"
 
 ########################################
+## Parse Args
+
+path="$1"
+fullpath="$media/$path"
+if [[ -n "$path" && ! -f "$fullpath" ]]
+then echo "$fail File does not exist at $fullpath" && exit 1
+fi
+
+########################################
 ## Helper Functions
 
 function getCreateDate {
@@ -52,21 +61,11 @@ function getCreateDate {
 }
 
 ########################################
-## Gather list of files
+## Verify Media
 
-index="$media/index.sqlite"
-if [[ ! -f "$index" ]]
-then sqlite3 "$index" "create table media(hash varchar(64) primary key, path text);"
-fi
+function verifyMedia {
 
-if ! all_files=$(sqlite3 "$index" "select path from media;")
-then echo "$fail Failed to select file paths from $index" && exit 1
-fi
-
-echo "Verifying $(echo "$all_files" | wc -l) media files"
-for file in $all_files
-do
-
+  file="$1"
   hasErr="false"
 
   ########################################
@@ -74,7 +73,7 @@ do
 
   fullpath="$media/$file"
   if [[ ! -f "$fullpath" ]]
-  then echo "$fail No file exists at path $fullpath" && continue
+  then echo "$fail No file exists at path $fullpath" && return
   fi
 
   ########################################
@@ -110,4 +109,30 @@ do
   then echo "$good Validated $file"
   fi
 
-done
+}
+
+########################################
+## Verify Provided File
+
+if [[ -n "$path" ]]
+then verifyMedia "$path"
+else
+
+  ########################################
+  ## Or Verify All Files
+
+  index="$media/index.sqlite"
+  if [[ ! -f "$index" ]]
+  then sqlite3 "$index" "create table media(hash varchar(64) primary key, path text);"
+  fi
+
+  if ! all_files=$(sqlite3 "$index" "select path from media;")
+  then echo "$fail Failed to select file paths from $index" && exit 1
+  fi
+
+  echo "Verifying $(echo "$all_files" | wc -l) media files"
+  for file in $all_files
+  do verifyMedia "$file"
+  done
+
+fi
